version: "3.9"

services:
  jotihunt:
    build: .
    image: jasperroel/jotihunt-site
    depends_on:
    - db
    environment:
      DATABASE_URL: postgres://jotihunt:jotihunt@db:5432/jotihunt
    expose:
    - "80"
    ports:
    - "5050:80"
    volumes:
      - .:/var/www/html

  pgadmin:
    image: dpage/pgadmin4
    restart: on-failure
    expose:
      - "80"
    ports:
      - "8081:80"
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.org
      PGADMIN_DEFAULT_PASSWORD: admin
  db:
    image: postgres
    ports:
      - "54321:5432"
    environment:
      POSTGRES_USER: jotihunt
      POSTGRES_PASSWORD: jotihunt
      TZ: Europe/Amsterdam
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
