version: "3.9"

services:
  jotihunt:
    build: .
    image: jasperroel/jotihunt-site
    depends_on:
    - db
    environment:
      DATABASE_URL: postgres://jotihunt:jotihunt@db:5432/jotihunt
    expose:
    - "80"
    ports:
    - "5050:80"
    volumes:
      - .:/var/www/html

  pgadmin:
    image: dpage/pgadmin4
    restart: on-failure
    ports:
      - "8081:80"
#    volumes:
#      - ./docker/2021-dump:/pgadmin4/2021-dump.backup
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@jotihunters.nl
      PGADMIN_DEFAULT_PASSWORD: akq*yzg-rpt-UCF5uem
  db:
    image: postgres
    environment:
      POSTGRES_USER: jotihunt
      POSTGRES_PASSWORD: jotihunt
